[project]
name = 'Tokenized-Healthcare-Precision-Aging-Research'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.biomaker-discovery]
path = 'contracts/biomaker-discovery.clar'
clarity_version = 2
epoch = 2.5

[contracts.intervention-testing]
path = 'contracts/intervention-testing.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
